# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProjectPublisher
                                 A QGIS plugin
 Publish your project to QWC2 easily with qwc-project-publisher-service
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-26
        copyright            : (C) 2022 by Nicolas AUBIN
        email                : aubinnic@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ProjectPublisher class from file ProjectPublisher.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .project_publisher import ProjectPublisher
    return ProjectPublisher(iface)
